# Generated by Django 4.1.3 on 2023-12-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Подзаголовок'),
        ),
    ]
