# Generated by Django 4.1.3 on 2023-12-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0002_alter_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файловый браузер',
            },
        ),
    ]
