# Generated by Django 4.1.3 on 2024-02-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0005_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='card_display',
            field=models.CharField(choices=[('default', 'Фото + Заголовок'), ('fullscreen', 'Фото на всю ширину + Заголовок поверх фото')], default='default', max_length=20, verbose_name='Вид карточки'),
        ),
    ]
