# Generated by Django 4.1.3 on 2024-02-27 18:34

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0009_post_img_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Текст записи'),
        ),
    ]
