# Generated by Django 4.1.3 on 2024-03-04 11:02

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0011_post_page_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название шаблона')),
                ('content', django_summernote.fields.SummernoteTextField(verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'Статический шаблон',
                'verbose_name_plural': 'Статические шаблоны',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='month',
            field=models.CharField(choices=[('Январь', 'Январь'), ('Январь/Февраль', 'Январь/Февраль'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Июль/Август', 'Июль/Август'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=20, verbose_name='Месяц'),
        ),
    ]
