# Generated by Django 4.1.3 on 2024-02-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image_mobile', models.ImageField(upload_to='banners/', verbose_name='Изображение (мобильное), размер 360*80 px')),
                ('image_tablet', models.ImageField(upload_to='banners/', verbose_name='Изображение (планшет), размер 670*150 px')),
                ('image_desktop', models.ImageField(upload_to='banners/', verbose_name='Изображение (десктоп), размер 940*150 px')),
                ('place', models.CharField(blank=True, default='default', max_length=100, verbose_name='Место расположения баннера')),
                ('url', models.URLField(verbose_name='URL')),
                ('show_on_main', models.BooleanField(default=True, verbose_name='Показывать на главной странице')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
