# Generated by Django 4.1.3 on 2024-03-12 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0012_statictemplate_alter_post_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('work_phone', models.CharField(blank=True, max_length=20, verbose_name='Рабочий телефон')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, upload_to='profile_photos', verbose_name='Фото')),
                ('cover_photo', models.ImageField(blank=True, upload_to='cover_photos', verbose_name='Обложка')),
                ('is_author', models.BooleanField(default=False, verbose_name='Автор')),
                ('is_personal', models.BooleanField(default=False, verbose_name='Член ред.коллегии')),
                ('tags', models.ManyToManyField(related_name='user_profiles', to='post_page.tag', verbose_name='Теги')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_page.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile')),
            ],
            options={
                'verbose_name': 'Авторский тег',
                'verbose_name_plural': 'Авторские теги',
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
