# Generated by Django 5.0.4 on 2024-04-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_usersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporatesubscription',
            options={'verbose_name': 'Подписка Юр-лиц', 'verbose_name_plural': 'Подписка Юр-лиц'},
        ),
    ]
